package render

import (
	"os"
    "strings"
	"fmt"
	"time"
    "iptables_interface/model"
)

func WriteToFile(rs model.Ruleset, path string) error {
	bytes := []byte(Export(rs))
	return os.WriteFile(path, bytes, 0600)
}

func Export(rs model.Ruleset) string {
	var sb strings.Builder

	t := time.Now()
	sb.WriteString(fmt.Sprintf("# Generated by iptables-interface on %s\n", t.Format("20060102150405")))
	
	// HARDCODED for scope of project rn
	sb.WriteString("*filter\n")

	sb.WriteString(fmt.Sprintf(":INPUT %s [0:0]\n", rs.Input.Policy))
	sb.WriteString(fmt.Sprintf(":OUTPUT %s [0:0]\n", rs.Output.Policy))
	sb.WriteString(fmt.Sprintf(":FORWARD %s [0:0]\n", rs.Forward.Policy))

	for _, v := range rs.Input.Rules {
		sb.WriteString(buildRule(rs.Input.ChainName, v))
	}

	for _, v := range rs.Output.Rules {
		sb.WriteString(buildRule(rs.Output.ChainName, v))
	}

	for _, v := range rs.Forward.Rules {
		sb.WriteString(buildRule(rs.Forward.ChainName, v))
	}

	sb.WriteString("COMMIT\n")
	return sb.String()
}

func buildRule(chainName model.ChainName, rule model.Rule) string {
	var sb strings.Builder
	
	if rule.Comment != "" {
		sb.WriteString(fmt.Sprintf("# %s\n", rule.Comment))
	}

	sb.WriteString(fmt.Sprintf("-A %s ", chainName))

	if rule.Protocol != "" {
		sb.WriteString(fmt.Sprintf("-p %s ", rule.Protocol))
	}
	// if rule.SrcIP != "" {} - Not in presets
	// if rule.DstIP != "" {} - Not in presets
	if rule.InIface != "" {
		sb.WriteString(fmt.Sprintf("-i %s ", rule.InIface))
	}
	if rule.OutIface != "" {
		sb.WriteString(fmt.Sprintf("-o %s ", rule.OutIface))
	}
	if rule.SrcPort != "" {
		sb.WriteString(fmt.Sprintf("--sport %s ", rule.SrcPort))
	}
	if rule.DstPort != "" {
		sb.WriteString(fmt.Sprintf("--dport %s ", rule.DstPort))
	}
	if rule.ConntrackState != "" {
		sb.WriteString(fmt.Sprintf("-m conntrack --ctstate %s ", rule.ConntrackState))
	}
	sb.WriteString(fmt.Sprintf("-j %s\n", rule.Target))

	return sb.String()
}